### PR TITLE
Introduction of computed property, fixes #18440.

### PR DESCRIPTION
**Pull request by asudoh**
It's a common use case of dojo/Stateful and dojox/mvc/StatefulArray to compute a property from two or more of them. e.g. Full name equals first name plus last name, Count of complete todos equals the sum of 1 for complete todos and 0 for incomplete todos.
Some discussions can be found at: ​https://github.com/tastejs/todomvc/pull/1101/files#r22573875 as well as ​http://dojo-toolkit.33424.n3.nabble.com/Binding-to-a-Stateful-s-computed-property-td3990310.html

### CODE REVIEW

**Comment by wkeese** [comment]
I looked over this very briefly but it seems good to me, other than those dojodoc issues.

**Comment by asudoh** [comment]
@wkeese Thank you for reviewing. Fixed DojoDoc issue: https://github.com/asudoh/dojox/commit/38fdda8edca14c78b71bf418c8e42d981be62b4d

**Comment by edchat** [comment]
Hi Asudoh, I was trying to run the tests with this update and doh_mvc_loan-stateful is failing for me, I assume it was working for you.  I also had a problem with the StoreRefControllerTest before your change because it was using a file from dojo/tests/stores which no longer exists, I will fix that once we figure out what is going on with loan-stateful.

**Comment by edchat** [comment]
Well, maybe it was a cache problem, it seems to be working now. I was getting an error when creating the pie chart.

**Comment by asudoh** [comment]
Thanks @edchat for taking a look, the loan test seems to require browser window to be activated, which may have been the cause of the test failures you saw.

**Comment by asudoh** [comment]
Squashed the two commits: https://github.com/asudoh/dojox/commit/a56c1be3e7ccdc2d9285fdec11a5427260983b75

**Comment by edchat** [comment]
Merged, thanks asudoh.

**Pull request closed without merging**
