### PR TITLE
set default input value for dojox/mobile/Switch - Fixes ticket #17873

### PR DESCRIPTION
**Pull request by SanDooo**

### CODE REVIEW

**Comment by dylans** [comment]
@cjolif this looks fine to me, any concerns about this change?

**Comment by pruzand** [comment]
@tkrugg since you're the owner of the ticket, could you review the PR and confirm it adresses the problem described in the ticket ?

**Comment by tkrugg** [comment]
Sorry for the late reply.

Correct me if I'm wrong but I think we want the switch to behave like a checkbox regarding forms
Both before and after this fix, although the switch behaved differently, it does not behave like a checkbox

*how checkboxes behave*
- they appear in the query string only when checked  (whether they were checked by the user or initialized as checked)

*how switches work, without the fix*

- They always appear in the query string
- If left to their initial value, they show "" (undefined) in the query string. Initial value isn't sent in the query string
- If toggled, they show "on" or "off" in the query string.
see [fiddle](https://jsfiddle.net/cjh9dr0o/5/embedded/result/)

*how switches work, with the fix*

- They always appear in the query string
- If left to their initial value, they show "on" or "off" in the query string. Initial value *is* sent in the query string `<-- change brought by the fix`
- If toggled, they show "on" or "off" in the query string.

Yes, the PR **is** addressing the issue, but I'm wondering: don't we want it to work like a checkbox?

**Comment by pruzand** [comment]
There're two things here as you mention.
For the patch itself, I'm not willing to change the behavior of the switch in a patch as it could have bad effects on existing code that may rely on the current behavior.
For the behavior of the switch, this is an enhancement that should only go into a new release. As we are today, we don't have the bandwith to do that for 1.11. 

So since you confirm the PR is fixing the issue, I will merge it.
Thx for your investigation.

**Comment by pruzand** [comment]
@SanDooo did you fill a CLA ? (https://github.com/dojo/dojox/blob/master/CONTRIBUTING.md)

**Comment by SanDooo** [comment]
Yes I have, on October 1st iirc.

**Comment by pruzand** [comment]
Merged in fe1b49a
Thanks @SanDooo for the PR.

**Pull request closed without merging**
