### PR TITLE
Fix for 17860

### PR DESCRIPTION
**Pull request by ben8p**
dojox.mdnd.* and dojox.layout.GridContainerLite does not work when there
is more than one dojo instance

### CODE REVIEW

**Comment by alisol911** [comment]
this commit breaks "dojox/widget/tests/test_PortletInGridContainerColumns.html", this test does not work as before

**Comment by alisol911** [comment]
also dojox/layout/tests/test_GridContainer.html is is not because in https://github.com/dojo/dojox/blob/master/layout/GridContainerLite.js#L411 , this.constructor.superclass.getChildren calls GridContainer.getChildren instead of _TemplatedMixin.getChildren

**Comment by ben8p** [comment]
Hmmm, I think I messed up when trying to resolve merge conflict (in order to start fixing the tests)...
that has closed the PR...
I will make a new one.

**Comment by ben8p** [comment]
@alisol911 thanks for the feedback.

@dylans I've updated it. It can be merged.

**Comment by dylans** [comment]
Thanks, closed via 6c0b08d

**Pull request closed without merging**
