### PR TITLE
Update form/BusyButton to make it usable in AMD.

### PR DESCRIPTION
**Pull request by mattiaslundberg**
Break out the different buttons from form/BusyButton to make them usable in AMD.

### CODE REVIEW

**Comment by wkeese** [comment]
Why did you close this?  The change hasn't been pushed yet.

**Comment by wkeese** [comment]
Hi @mattiaslundberg.  Thanks for the patch, but don't you need to update the test file(s) too?

**Comment by mattiaslundberg** [comment]
Hi, I have updated the BusyButton test cases so they don't fail with parsing errors. Is there something more that needs to be updated in the tests?

**Comment by wkeese** [comment]
@mattiaslundberg - OK, thanks.  Ideally, since this PR is (in your own words) to "Update form/BusyButton to make it usable in AMD", you would update the tests to show that the widgets are indeed usable in AMD.

**Comment by wkeese** [comment]
PS: I suppose just updating the dojoType="foo.bar" declarations to use slashes instead of dots will prove that it works with AMD?

**Comment by mattiaslundberg** [comment]
Have updated the test, changing the declarations to use slash instead of dots makes the current master fail the test with parsing error/404. The test works after this change is applied.

**Comment by wkeese** [comment]
OK thanks, I pushed it as 8672a8981b4da1332df2a793414f535381b0268f.

**Pull request merged**
