### PR TITLE
Added Id Referencing to the toJson function

### PR DESCRIPTION
**Pull request by mdavisJr**
Provides the option to use Id Referencing in the toJson function by setting the idAttribute parameter.  If idAttribute parameter is left undefined, the toJson function will use JSONPath convention.  This allows Dojo's toJSON function to be compatible with JSON.NET.

### CODE REVIEW

**Comment by dylans** [comment]
Thanks for the proposed PR @mdavisRevSpringInc , sorry for the delay in responding to it. As part of our contributor guidelines, we need a CLA ( http://dojofoundation.org/about/cla ) on file. Please let us know once you've completed that. We're looking to get a Dojo 1.11 release done fairly soon, and have listed this as a candidate for that release, but would need to land this patch in the next week or two.

**Comment by mdavisRevSpringInc** [comment]
I just submitted my cla.  If there are any issues, please let me know.

**Comment by wkeese** [comment]
It seems strange to check this in without having even a manual test.  There's no way to test whether or not the code is working.

**Comment by dylans** [comment]
@wkeese I wasn't going to just blindly check it in, I was waiting for a CLA before reviewing. I think it's useful, so I'll either ask @mdavisRevSpringInc for a test case or I'll write one.

**Comment by mdavisRevSpringInc** [comment]
Do you need me to write a test case for this?

**Comment by dylans** [comment]
@mdavisRevSpringInc if you have time that would be great, otherwise I'll plan to add one sometime in the next week or so. https://github.com/dojo/dojo/blob/master/tests/README.md contains info about writing tests... even though most of the dojox tests are done currently with DOH, the tests for dojox/store use Intern ( https://github.com/dojo/dojox/tree/master/store/tests ), so feel free to follow the lead there to do the same. Thanks!

**Comment by mdavisRevSpringInc** [comment]
I'm just putting the finishing touches on the tests.  They should be ready tomorrow.

**Comment by dylans** [comment]
Closed via 5e668ac, thanks for the enhancement @mdavisJr !

Note that I allowed a few style guideline inconsistencies in here, because the code in this file is in rather bad shape and really I prefer a more modern style as well. I also noticed a few other minor issues with this file from JSHint. Fixed a couple of them, and added TODO for one that just doesn't make sense how it works currently.

**Pull request closed without merging**
