### PR TITLE
remove globals when not in use from dojox/string (#16753)

### PR DESCRIPTION
**Pull request by dylans**
Not sure anyone cares about this, but it should fix https://bugs.dojotoolkit.org/ticket/16753 .

### CODE REVIEW

**Comment by wkeese** [comment]
ISTM there are two standard patterns we use in dojox, and if anything you should update the code to use one of those patterns:

1. import the dojox variable

```js
define([
	".",
	...
], function(dojox, ...){
	lang.getObject("mobile", true, dojox);
	...
});
```

2. specify everything in string argument to `getObject()`:

```js
var plugins = lang.getObject("dojox.analytics.plugins", true);
```

Both of these approaches work due to code in the Dojo V1 loader and also `getObject()` where the dojox variable is remapped to point wherever djConfig said.

**Comment by dylans** [comment]
Looking at this again, I'm wondering if I can just include dojox/string as a dependency since this module is simply adding features to that singleton, and skip the whole global check?

**Comment by wkeese** [comment]
Except, there isn't any dojox/string.js file (or a dojox/string/main.js, or anything like that), is there?

I just noticed that every file in the dojox/string directory, except for tokenize.js, has the same problem with accessing `dojox` as a global variable.

**Comment by dylans** [comment]
Yes, it's a strange design. I don't know why a stub wasn't created as dojox/string... I was thinking of just making a stub module to solve that.

**Comment by wkeese** [comment]
Sure, that would be fine too, although it seems unnecessary.

The current design isn't so unusual; there are other similar packages like dojox/html and dojox/math.  Although those directories have _base.js files, they aren't required by the other JS files.

In any case it's probably best to just do a trivial fix to this problem.   You should only need to change a few lines in each file, like I wrote above.

**Comment by dylans** [comment]
Fair enough, I'll make that change soon.

**Comment by dylans** [comment]
Will rework this after 1.11.

**Pull request closed without merging**
