### PR TITLE
#14228 dojox.grid.DataGrid accessibility violation

### PR DESCRIPTION
**Pull request by chenzhh**
dojox.grid.DataGrid triggers accessibility DAP violation : The WAI ARIA role does not meet implicit ARIA semantic restriction(s) for the element

Set unselecteable checkbox to aria-hidden=true

### CODE REVIEW

**Comment by dylans** [comment]
Ok, I can land this, though I'm not sure why there is a reference to #14228, which doesn't seem like the right ticket? Can you verify that was the intended Dojo bug number @chenzhh ?

**Comment by cjolif** [comment]
@dylans this is an internal IBM ticket I suspect... I can handle this one if you want to (this would need to be backported as well).

**Comment by dylans** [comment]
@cjolif, ok, go ahead, thanks!

**Comment by cjolif** [comment]
merged in 0c8fa5e286ef38b369d37f7c3b24c27274eeea55 and 494fdaba0cc0cd1ee8f594e482347a396edf7bc3. thanks @chenzhh.

**Comment by dylans** [comment]
Closed per @cjolif's previous comment and commits.

**Pull request closed without merging**
