### PR TITLE
Case insensitive entity matching fix, fixes #18505, refs #t18505

### PR DESCRIPTION
**Pull request by Kagetsume**
This is a minor fix to the html entities so that it does case insensitive matching.

### CODE REVIEW

**Comment by Kagetsume** [comment]
I need to do more testing on the pull, just wanted to get an initial out there.

**Comment by dylans** [comment]
@Kagetsume the change to make the regex case insensitive is straightforward, so I'm fine with the change from a code perspective.

**Comment by Kagetsume** [comment]
Had to make another small change so that the map lookup was normalized as well, it wasn't just the gi, unfortunately.   Found that with some testing.  End change is still pretty simple.

**Comment by neonstalwart** [comment]
how about a test to prevent regression?

**Comment by Kagetsume** [comment]
Actually, I just invalidated the bug.  I was reminded why I didn't implement it in the first place when I wrote it; case matters for a chunk of entities.   Closing pull.  Not a good fix.

**Pull request closed without merging**
