### PR TITLE
Add Basque language to 1.10 branch (#18560)

### PR DESCRIPTION
**Pull request by DominiquePicard**

### CODE REVIEW

**Comment by wkeese** [comment]
Stop filing tickets against branches. As I explained in dojo/dojo#150, dojo/dojo#149, dojo/dijit#89, and dojo/dijit#90, PR's should be against master.

**Comment by cjolif** [comment]
The PR agains the branch is different than the PR against master, because properties where added in between. So I think this was useful to prevent the commiter to have to himself "guess" what properties have to be removed.

**Comment by wkeese** [comment]
OK, I see that PR #172 (for master) has 977 lines, PR #171 (for 1.10) also has 977, but PR #173 (1.9) has 711 lines. So I guess this is an exceptional case where it makes sense to have a separate PR for the 1.9 branch.  Presumably though this PR is identical to the master one?

**Comment by cjolif** [comment]
yes 1.10 & master were identical and so one could have been avoided.

**Pull request closed without merging**
